### ISSUE TITLE
Pregledanje rada

### ISSUE THREAD

**Issue by dekanac** [MATF-RG17/RG163-vortex-game#1]

**Comment by ivan-cukic-matf** [comment]
Otvorite ponovo ovaj issue kad zavrsite #2

**Comment by dekanac** [comment]
Popravio sam celokupno osvetljenje. Inace, sto se tice koda, funkcije su pocele da dobijaju srpske nazive kad mi je ponestalo inspiracije da ih imenujem na engleskom :)

**Comment by ivan-cukic-matf** [comment]
Otvorite kad završite #3
